# root of datasets for testing
# empty string is neglected
ADE20K = ''
BDD100K = ''
Cityscapes = ''
CityscapesCategory = ''
CityscapesFull = ''
coco = ''
"coco[voc]" = ''
LIP = ''
Mapillary = ''
SBD = ''
VOC = ''
